# 项目名称
project_name: xxx项目名称

env: 测试环境

# 执行人
tester_name: 陈鑫

host: https://www.baidu.com/

# 浏览器驱动路径和需要启动的浏览器
driver:
  path: macm1/chromedriver
  browser: chrome

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
notification_type: 0

# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 邮箱信息
email:
  # 发件人邮箱
  send_user:
  email_host: smtp.qq.com
  # 授权。自己到QQ邮箱中配置stamp_key
  stamp_key:
  # 收件人邮箱
  send_list:

# 钉钉机器人信息
ding_talk:
  webhook: # 需要创建钉钉机器人后获取，自行百度吧
  secret:  # 需要创建钉钉机器人后获取，自行百度吧

# 飞书通知
lark:
  webhook:

# 企业通知的相关配置
wechat:
  webhook:


# 数据库信息
mysql_db:
  host:
  user:
  password:
  database:
  port: